name: Build and Draft Release

on:
  push:
    tags:
      - "v*.*.*"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup .NET 8 LTS
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: "8.0.x"

      - name: Setup .NET 9
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: "9.0.x"

      - name: Install Dalamud
        run: |
          rm -rf $HOME/.xlcore
          mkdir -p $HOME/.xlcore/dalamud/Hooks/dev
          curl -L https://goatcorp.github.io/dalamud-distrib/latest.zip -o dalamud.zip
          unzip -o dalamud.zip -d $HOME/.xlcore/dalamud/Hooks/dev
          echo "----- Final Hooks/dev tree -----"
          ls -R $HOME/.xlcore/dalamud/Hooks/dev

      - name: Restore dependencies
        run: dotnet restore NoQuestIcons.csproj

      - name: Build project
        run: dotnet build NoQuestIcons.csproj --configuration Release --no-restore

      - name: Publish artifact
        run: |
          mkdir -p output
          cp bin/Release/*.dll output/
          cp NoQuestIcons.json output/
          # Optional: include these if you want them in the release zip
          cp README.md output/ || true
          cp LICENSE output/ || true
          cp pluginmaster.json output/ || true
          cp images/HQIcon.png output/ || true
          cd output
          zip -r ../NoQuestIcons-${{ github.ref_name }}.zip .
          cd ..

      - name: Draft GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          draft: true
          files: NoQuestIcons-${{ github.ref_name }}.zip
