name: Build and Draft Release

on:
  push:
    tags:
      - "v*.*.*"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup .NET 9.0
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '9.0.x'

      - name: Download and unpack Dalamud runtime
        run: |
          curl -L https://goatcorp.github.io/dalamud-distrib/latest.zip -o dalamud.zip
          mkdir -p $HOME/.xlcore/dalamud/Hooks/dev
          unzip -q dalamud.zip -d $HOME/.xlcore/dalamud/Hooks/dev
          echo "----- Folder structure after unzip -----"
          ls -R $HOME/.xlcore/dalamud/Hooks/dev

          # If Dalamud.dll is nested deeper, move it up
          DLL_PATH=$(find $HOME/.xlcore/dalamud/Hooks/dev -name Dalamud.dll | head -n 1 || true)
          if [ -n "$DLL_PATH" ]; then
            echo "Found Dalamud.dll at: $DLL_PATH"
            cp -u "$DLL_PATH" $HOME/.xlcore/dalamud/Hooks/dev/
          else
            echo "ERROR: Dalamud.dll not found in extracted zip"
          fi

          echo "----- Final Hooks/dev contents -----"
          ls -l $HOME/.xlcore/dalamud/Hooks/dev

      - name: Restore dependencies
        run: dotnet restore

      - name: Build plugin
        run: dotnet build NoQuestIcons/NoQuestIcons.csproj --configuration Release --no-restore

      - name: Package plugin
        run: |
          mkdir package
          cp NoQuestIcons/bin/Release/net9.0*/NoQuestIcons.dll package/
          cp NoQuestIcons.json package/
          zip -j NoQuestIcons.zip package/*

      - name: Upload build artifact
        uses: actions/upload-artifact@v4
        with:
          name: NoQuestIcons-zip
          path: NoQuestIcons.zip
          if-no-files-found: error
