name: Build and Draft Release

on:
  push:
    tags:
      - "v*"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Ensure UTF-8 without BOM
        run: |
          echo "Normalizing YAML encoding..."
          iconv -f utf-8 -t utf-8 -c .github/workflows/release.yml > tmp.yml
          mv tmp.yml .github/workflows/release.yml

      - name: Set up .NET 8 LTS
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: "8.0.x"

      - name: Set up .NET 9
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: "9.0.x"

      - name: Install Dalamud
        run: |
          rm -rf $HOME/.xlcore
          mkdir -p $HOME/.xlcore/dalamud/Hooks/dev
          curl -L https://goatcorp.github.io/dalamud-distrib/latest.zip -o dalamud.zip
          unzip -o dalamud.zip -d $HOME/.xlcore/dalamud/Hooks/dev
          echo "----- Final Hooks/dev tree -----"
          ls -R $HOME/.xlcore/dalamud/Hooks/dev

      - name: Restore dependencies
        run: dotnet restore NoQuestIcons.csproj

      - name: Build project
        run: dotnet build NoQuestIcons.csproj --configuration Release --no-restore

      - name: Prepare output
        run: |
          mkdir -p output
          cp bin/Release/net*/NoQuestIcons.dll output/
          cp NoQuestIcons.json output/
          cp pluginmaster.json output/

      - name: Upload build artifact
        uses: actions/upload-artifact@v4
        with:
          name: NoQuestIcons
          path: output/*

      - name: Draft GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          draft: true
          files: output/*
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
