name: Build and Draft Release

on:
  push:
    tags:
      - "v*.*.*"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup .NET 9.0
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '9.0.x'

      # Install Dalamud exactly where the SDK checks
      - name: Download Dalamud runtime
        run: |
          curl -L https://goatcorp.github.io/dalamud-distrib/latest.zip -o dalamud.zip
          mkdir -p $HOME/.xlcore/dalamud/Hooks/dev
          unzip -q dalamud.zip -d $HOME/.xlcore/dalamud/Hooks/dev
          echo "Checking for Dalamud.dll..."
          find $HOME/.xlcore/dalamud/Hooks/dev -name Dalamud.dll

      - name: Restore dependencies
        run: dotnet restore

      - name: Build plugin
        run: dotnet build NoQuestIcons/NoQuestIcons.csproj --configuration Release --no-restore

      - name: Package plugin
        run: |
          mkdir package
          cp NoQuestIcons/bin/Release/net9.0*/NoQuestIcons.dll package/
          cp NoQuestIcons.json package/
          zip -j NoQuestIcons.zip package/*

      - name: Upload build artifact
        uses: actions/upload-artifact@v4
        with:
          name: NoQuestIcons-zip
          path: NoQuestIcons.zip
          if-no-files-found: error

      - name: Create GitHub Release Draft
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ github.ref_name }}
          name: Release ${{ github.ref_name }}
          body: "Automated release for ${{ github.ref_name }}"
          draft: true
          files: |
            NoQuestIcons.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
