name: Build and Draft Release

on:
  push:
    tags:
      - "v*"

permissions:
  contents: write   # 👈 needed for creating releases with GITHUB_TOKEN

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      # Install .NET runtimes & SDKs
      - name: Setup .NET 8 (LTS)
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x

      - name: Setup .NET 9 (Latest)
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 9.0.x

      # Install Dalamud runtime
      - name: Setup Dalamud
        run: |
          rm -rf $HOME/.xlcore
          mkdir -p $HOME/.xlcore/dalamud/Hooks/dev
          curl -L https://goatcorp.github.io/dalamud-distrib/latest.zip -o dalamud.zip
          unzip -o dalamud.zip -d $HOME/.xlcore/dalamud/Hooks/dev
          echo "----- Dalamud installed -----"
          ls -R $HOME/.xlcore/dalamud/Hooks/dev

      # Restore dependencies
      - name: Restore dependencies
        run: dotnet restore NoQuestIcons.csproj

      # Build plugin
      - name: Build project
        run: dotnet build NoQuestIcons.csproj --configuration Release --no-restore

      # Package build outputs
      - name: Package plugin
        run: |
          mkdir -p output
          cp bin/Release/net*/NoQuestIcons.dll output/ || true
          cp bin/Release/net*/NoQuestIcons.pdb output/ || true
          cp NoQuestIcons.json output/ || true
          echo "Output folder contents:"
          ls -R output

      # Create GitHub release
      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          files: output/*
        env:
          # Prefer PAT if set, fallback to GITHUB_TOKEN
          GITHUB_TOKEN: ${{ secrets.PAT_TOKEN || secrets.GITHUB_TOKEN }}
