name: Build and Draft Release

on:
  push:
    tags:
      - "v*"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Normalize file encoding (UTF-8 without BOM)
        run: |
          echo "Normalizing all source files to UTF-8 without BOM..."
          find . -type f \( -name "*.cs" -o -name "*.json" -o -name "*.yml" -o -name "*.yaml" -o -name "*.md" -o -name "*.txt" \) \
            -exec sh -c 'iconv -f utf-8 -t utf-8 -c "$1" > "$1.tmp" && mv "$1.tmp" "$1"' sh {} \;

      - name: Set up .NET 8 LTS
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: "8.0.x"

      - name: Set up .NET 9
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: "9.0.x"

      - name: Install Dalamud
        run: |
          rm -rf $HOME/.xlcore
          mkdir -p $HOME/.xlcore/dalamud/Hooks/dev
          curl -L https://goatcorp.github.io/dalamud-distrib/latest.zip -o dalamud.zip
          unzip -o dalamud.zip -d $HOME/.xlcore/dalamud/Hooks/dev
          echo "----- Final Hooks/dev tree -----"
          ls -R $HOME/.xlcore/dalamud/Hooks/dev

      - name: Restore dependencies
        run: dotnet restore NoQuestIcons.csproj

      - name: Build project
        run: dotnet build NoQuestIcons.csproj --configuration Release --no-restore

      - name: Prepare output
        run: |
          mkdir -p output
          cp bin/Release/net*/NoQuestIcons.dll output/
          cp NoQuestIcons.json output/
          cp pluginmaster.json output/

      - name: Upload build artifact
        uses: actions/upload-artifact@v4
        with:
          name: NoQuestIcons
          path: output/*

      - name: Draft GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          draft: true
          files: output/*
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
