name: Build and Draft Release

on:
  push:
    tags:
      - "v*.*.*" # triggers only on version tags like v1.0.2

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup .NET 9.0
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '9.0.x'

      # Create dummy Dalamud folder to satisfy Dalamud.NET.Sdk
      - name: Create dummy Dalamud folder
        run: mkdir -p ${{ github.workspace }}/.dalamud/Hooks/dev

      - name: Restore dependencies
        run: dotnet restore

      - name: Build plugin
        run: dotnet build --configuration Release --no-restore -p:DisableDalamudLibCh
