name: Build and Release

on:
  push:
    tags:
      - "v*"

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup .NET (LTS runtime + 9.0 SDK)
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: |
            8.0.x
            9.0.x

      - name: Install Dalamud dev libs
        shell: bash
        run: |
          set -euo pipefail
          rm -rf "$HOME/.xlcore"
          mkdir -p "$HOME/.xlcore/dalamud/Hooks/dev"
          curl -L https://goatcorp.github.io/dalamud-distrib/latest.zip -o dalamud.zip
          unzip -o dalamud.zip -d "$HOME/.xlcore/dalamud/Hooks/dev" >/dev/null
          echo ">> Installed Dalamud dev libs to $HOME/.xlcore/dalamud/Hooks/dev"

      - name: Restore
        run: dotnet restore NoQuestIcons.csproj

      - name: Build
        env:
          VERSION: ${{ github.ref_name }}
        run: |
          VER="${VERSION#v}"
          echo "Building version: $VER"
          dotnet build NoQuestIcons.csproj --configuration Release --no-restore -p:Version="$VER"

      - name: Show build tree
        run: |
          echo "== ls -la =="
          ls -la
          echo "== bin/Release =="
          ls -la bin/Release || true

      - name: Package outputs (include manifest)
        run: |
          set -euo pipefail
          mkdir -p output
          cp "bin/Release/NoQuestIcons.dll" "output/NoQuestIcons.dll"
          if [ -f "bin/Release/NoQuestIcons.pdb" ]; then
            cp "bin/Release/NoQuestIcons.pdb" "output/NoQuestIcons.pdb"
          fi
          cp "manifest.json" "output/manifest.json"

          # Stable name for pluginmaster (latest)
          (cd output && zip -r "NoQuestIcons.zip" .)

          # Optional: versioned zip too
          (cd output && zip -r "NoQuestIcons-${{ github.ref_name }}.zip" .)

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: NoQuestIcons-${{ github.ref_name }}
          path: output/*

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ github.ref_name }}
          name: NoQuestIcons ${{ github.ref_name }}
          draft: false
          prerelease: false
          generate_release_notes: true
          files: |
            output/NoQuestIcons.dll
            output/NoQuestIcons.pdb
            output/NoQuestIcons.zip
            output/NoQuestIcons-${{ github.ref_name }}.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
