name: Build and Release

on:
  push:
    tags:
      - 'v*.*.*'   # runs when you push a version tag like v1.2.3

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: |
            8.0.x
            9.0.x

      - name: Setup Dalamud SDK
        run: |
          rm -rf $HOME/.xlcore
          mkdir -p $HOME/.xlcore/dalamud/Hooks/dev
          curl -L https://goatcorp.github.io/dalamud-distrib/latest.zip -o dalamud.zip
          unzip -o dalamud.zip -d $HOME/.xlcore/dalamud/Hooks/dev

      - name: Restore
        run: dotnet restore NoQuestIcons/NoQuestIcons.csproj

      - name: Build
        run: dotnet build NoQuestIcons/NoQuestIcons.csproj --configuration Release --no-restore

      - name: Package
        run: |
          mkdir -p output
          cp NoQuestIcons/bin/Release/net*/NoQuestIcons.dll output/
          cp NoQuestIcons/bin/Release/net*/NoQuestIcons.pdb output/ || true
          cp NoQuestIcons/NoQuestIcons.json output/
          cd output
          zip NoQuestIcons.zip NoQuestIcons.dll NoQuestIcons.pdb NoQuestIcons.json

      - name: Upload Release Assets
        uses: softprops/action-gh-release@v2
        with:
          files: |
            output/NoQuestIcons.dll
            output/NoQuestIcons.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
