name: Build and Draft Release

on:
  push:
    tags:
      - "v*.*.*"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup .NET 9.0
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '9.0.x'

      - name: Restore dependencies
        run: dotnet restore

      # 👇 Key fix: skip Dalamud runtime validation
      - name: Build plugin
        run: dotnet build NoQuestIcons/NoQuestIcons.csproj --configuration Release --no-restore -p:DisableDalamudLibCheck=true

      - name: Package plugin
        run: |
          mkdir package
          cp NoQuestIcons/bin/Release/net9.0*/NoQuestIcons.dll package/
          cp NoQuestIcons.json package/
          zip -j NoQuestIcons.zip package/*

      - name: Upload build artifact
        uses: actions/upload-artifact@v4
        with:
          name: NoQuestIcons-zip
          path: NoQuestIcons.zip
          if-no-files-found: error

      - name: Extract changelog for this version
        id: changelog
        run: |
          version="${GITHUB_REF_NAME}" # e.g. v1.0.7
          if [ ! -f CHANGELOG.md ]; then
            echo "content=Release $version" >> $GITHUB_OUTPUT
            exit 0
          fi
          start=$(grep -n "## \[$version\]" CHANGELOG.md | cut -d: -f1)
          if [ -z "$start" ]; then
            echo "content=Release $version" >> $GITHUB_OUTPUT
            exit 0
          fi
          next=$(grep -n "## \[" CHANGELOG.md | awk -F: -v s=$start '$1 > s {print $1; exit}')
          if [ -z "$next" ]; then next=$(wc -l < CHANGELOG.md); fi
          content=$(sed -n "${start},$((next-1))p" CHANGELOG.md)
          echo "content<<EOF" >> $GITHUB_OUTPUT
          echo "$content" >> $GITHUB_OUTPUT
          echo "EOF" >> $GITHUB_OUTPUT

      - name: Create GitHub Release Draft
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ github.ref_name }}
          name: Release ${{ github.ref_name }}
          body: ${{ steps.changelog.outputs.content }}
          draft: true
          files: |
            NoQuestIcons.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
