name: Build and Draft Release

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:

permissions:
  contents: write   # needed to create a release and upload assets

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          persist-credentials: true

      - name: Setup .NET (LTS runtime + 9.0 SDK)
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: |
            8.0.x
            9.0.x

      - name: Install Dalamud dev libraries
        shell: bash
        run: |
          set -euo pipefail
          rm -rf "$HOME/.xlcore"
          mkdir -p "$HOME/.xlcore/dalamud/Hooks/dev"
          curl -sSL https://goatcorp.github.io/dalamud-distrib/latest.zip -o dalamud.zip
          unzip -o dalamud.zip -d "$HOME/.xlcore/dalamud/Hooks/dev"
          echo ">> Installed Dalamud dev libs to $HOME/.xlcore/dalamud/Hooks/dev"
          ls -la "$HOME/.xlcore/dalamud/Hooks/dev" | head -n 50

      - name: Restore
        run: dotnet restore NoQuestIcons.csproj

      - name: Build (force output path)
        run: |
          dotnet build NoQuestIcons.csproj \
            --configuration Release \
            --no-restore \
            -p:OutDir=${{ github.workspace }}/output/
          echo ">> Output contents:"
          ls -la ${{ github.workspace }}/output/

      - name: Verify artifact exists
        shell: bash
        run: |
          set -e
          test -f "${{ github.workspace }}/output/NoQuestIcons.dll" || { echo "NoQuestIcons.dll not found in output/"; exit 1; }

      - name: Draft GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          draft: true
          tag_name: ${{ github.ref_name }}
          files: |
            output/NoQuestIcons.dll
          generate_release_notes: true
